<?php
use Zend\Form\Element\Select;
use Zend\Form\Form;

$form = new Form("filter");

$form->prepare();

$options["All"] = array('label' => "All");
foreach($cities as $state => $cityArr) {
    $options[$state] = array('label' => $state, 'options' => $cityArr);
}
$element = new Select("city");
$element->setValueOptions($options)->setName("city")->setLabel("city")->setAttribute("class", "form-control")->setAttribute("id", "state");
?>
<form class="form">
    <ul class="list-group">
        <li class="list-group-item">

        <div class="form-group">
            <label for="jobTitle">Title</label>
            <input type="text" class="form-control input-lg" name="title" id="jobTitle" placeholder="Enter title for job" />
        </div>

        <div class="form-group">
            <label for="state">State</label>
            <?php echo $this->formSelect($element); ?>
        </div>

        <div class="form-group">
            <label for="text">Text</label>
            <textarea class="form-control" placeholder="Description of job (copy+paste)" id="text" cols="30" rows="10"></textarea>
        </div>

        <div class="form-group">
            <label for="source">Source of job post</label>
            <input type="text" class="form-control" placeholder="Source of vacancy" name="source" id="source" />
        </div>

        <div class="form-group">
            <label for="source">Link</label>
            <input type="text" class="form-control" placeholder="Link to job page or company website" name="link" id="link" />
        </div>

        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon" id="sizing-addon2"><span class="glyphicon glyphicon-time"></span></span>
                <input type="text" class="form-control" name="created" placeholder="Grab date"
                       aria-describedby="sizing-addon2"/>
            </div>
        </div>

        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon" id="sizing-addon3"><span class="glyphicon glyphicon-time"></span></span>
                <input type="text" class="form-control" name="created_original" placeholder="Original post date"
                       aria-describedby="sizing-addon3"/>
            </div>
        </div>

        </li>
        <li class="list-group-item" data-toggle="tooltip" data-placement="left" title="Mark job as" id="markAs"><div class="btn-group" data-toggle="buttons">
                <label class="btn btn-success">
                    <input type="checkbox" autocomplete="off"> Applied
                </label>
                <label class="btn btn-warning">
                    <input type="checkbox" autocomplete="off"> Favorite
                </label>
                <label class="btn btn-danger">
                    <input type="checkbox" autocomplete="off"> Denied
                </label>
                <label class="btn btn-primary">
                    <input type="checkbox" autocomplete="off"> No experience
                </label>
                <label class="btn btn-danger">
                    <input type="checkbox" autocomplete="off"> No H1B
                </label>
                <label class="btn btn-danger">
                    <input type="checkbox" autocomplete="off"> Unqualified
                </label>
                <label class="btn btn-default">
                    <input type="checkbox" autocomplete="off"> Hidden
                </label>
                <label class="btn btn-default">
                    <input type="checkbox" autocomplete="off"> Archived
                </label>
            </div></li>
    </ul>
    <input type="submit" value="Save" class="btn btn-success" />
</form>
<script type="text/javascript">
    $(document).ready(function() {
        $('#markAs').tooltip();
    })
</script>