<?php
use Zend\Form\Element\Select;
use Zend\Form\Form;

if(!isset($text)) {
	$text = "";
}

if(!isset($city)) {
	$city = "";
}
?>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">Filter jobs</span>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	<form class="navbar-form navbar-left" role="search" action="<?php echo $this->url('job', array('action'=>'search'));?>" method="post">
      <ul class="nav navbar-nav">
		  <li class="nav">
			  <?php
			  $form = new Form("filter");

			  $form->prepare();
			  //array_unshift($cities, "All");

              array(
                  array('label' => 'Jazz', 'options' =>
                      array(
                          'Acid',
                          'Cool',
                          'Smooth'
                      )
                  ),
                  array('label' => 'Rock',
                      'options' =>
                      array(
                          'Alternative Rock',
                          'Folk Rock',
                          'Garage Rock',
                          'Hard Rock',
                          'Heavy Metal'
                      )
                  )
              );


              /*echo "<pre>";
              var_dump($cities);
              echo "</pre>";*/

              $options["All"] = array('label' => "All");
              foreach($cities as $state => $cityArr) {
                  $options[$state] = array('label' => $state, 'options' => $cityArr);


                  //echo "$state $city \n";
              }
			  $element = new Select("city");

			  $element->setValueOptions($options)->setName("city")->setLabel("city");
			  $element->setValue($city);
              $form->add($element);

			  echo $this->formSelect($element);

			  ?>
		  </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Order by <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu" id="select_order_by">
            <li><a href="#" id="order_by_city">City</a></li>
            <li><a href="#" id="order_by_state">State</a></li>
			  <li class="divider"></li>
		  </ul>
        </li>
		  <li class="nav">
			  <a href="#" id="sort_by"><span class="glyphicon glyphicon-sort-by-attributes"></span></a>
		  </li>

      </ul>

        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search" name="text" value="<?php echo $text; ?>">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
		  <input type="hidden" name="order_by" id="order_by" value="" />
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<?php foreach ($paginator as $job) :
    if($job->hidden != "1") { ?>
        <ul class="list-group">
            <li class="list-group-item"><a
                    href="<?php echo $this->url('job', array('action' => 'view', 'id' => $job->id)); ?>"><?php echo $this->escapeHtml($job->title); ?></a>
            </li>
            <li class="list-group-item"><?php echo $this->escapeHtml($job->city); ?></li>
            <li class="list-group-item">
                <a href="<?php echo $this->escapeHtml($job->url); ?>">Open source of vacancy</a>
            </li>
            <li class="list-group-item"><span class="glyphicon glyphicon-time"></span> Grab
                date: <?php echo $this->escapeHtml($job->created); ?></li>
            <li class="list-group-item"><span class="glyphicon glyphicon-time"></span> Original post
                date: <?php echo $this->escapeHtml($job->created_original); ?></li>

            <?php if ($job->application_id != "" || $job->denied == "1" || $job->no_experience == "1" || $job->no_h1b == "1" || $job->unqualified == "1") { ?>
                <li class="list-group-item"><span class="glyphicon glyphicon-tags"></span>
                    <?php if ($job->application_id != "") { ?>
                        <span class="label label-success">Applied</span>
                    <?php }

                    if ($job->denied == "1") { ?>
                        <span class="label label-danger">Denied</span>
                    <?php }

                    if ($job->no_experience == "1") { ?>
                        <span class="label label-primary">No experience</span>
                    <?php }

                    if ($job->hidden == "1") { ?>
                        <span class="label label-success">Hidden</span>
                    <?php }

                    if ($job->no_h1b == "1") { ?>
                        <span class="label label-danger">No H1B</span>
                    <?php }

                    if ($job->unqualified == "1") { ?>
                        <span class="label label-primary">Unqualified</span>
                    <?php }
                    ?>
                </li>
            <?php } ?>
        </ul>
    <?php
    }

endforeach;


echo $this->paginationControl(
	// the paginator object
	$this->paginator,
	'sliding',
	// the partial to use to render the control
	array('partial/paginator.phtml', ''),
	// the route to link to when a user clicks a control link
	array(
		'route' => 'job'
	)
);
?>
<script type="text/javascript">
	$(document).ready(function() {
		/**
		 * simple event listeners for order by filter
		 */
		$('#order_by_city').click(function() {
			$('#order_by').val('city');
		});
		$('#order_by_state').click(function() {
			$('#order_by').val('state');
		});
	});
</script>