<?php
if(!isset($text)) {
	$text = "";
}
?>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">Filter jobs</span>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Order by <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu" id="select_order_by">
            <li><a href="#" id="order_by_title">Title</a></li>
            <li><a href="#" id="order_by_id">id</a></li>
            <li><a href="#" id="order_by_city">City</a></li>
            <li class="divider"></li>
            <li><a href="#" id="order_by_original_date">Original date</a></li>
            <li class="divider"></li>
            <li><a href="#" id="order_by_grab_date">Grab date</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search" action="<?php echo $this->url('job', array('action'=>'search'));?>" method="post">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search" name="text" value="<?php echo $text; ?>">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
		  <input type="hidden" name="order_by" id="order_by" value="" />
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<?php foreach ($jobs as $job) : ?>
<ul class="list-group">
	<li class="list-group-item"><a href="<?php echo $this->url('job', array('action'=>'view', 'id' => $job->id));?>"> <?php echo $this->escapeHtml($job->title);?></a></li>
	<li class="list-group-item"><?php echo $this->escapeHtml($job->city);?></li>
	<li class="list-group-item">
        <a href="<?php echo $this->escapeHtml($job->url); ?>">Open source of vacancy</a>
    </li>
	<li class="list-group-item"><span class="glyphicon glyphicon-time"></span> Grab date: <?php echo $this->escapeHtml($job->created);?></li>
	<li class="list-group-item"><span class="glyphicon glyphicon-time"></span> Original post date: <?php echo $this->escapeHtml($job->created_original);?></li>
</ul>
<?php endforeach; ?>
<script type="text/javascript">
	$(document).ready(function() {

		/**
		 * simple event listeners for order by filter
		 */

		$('#order_by_title').click(function() {
			$('#order_by').val('title');
		});
		$('#order_by_id').click(function() {
			$('#order_by').val('id');
		});
		$('#order_by_created_original').click(function() {
			$('#order_by').val('created_original');
		});
		$('#order_by_original_date').click(function() {
			$('#order_by').val('title');
		});
		$('#order_by_grab_date').click(function() {
			$('#order_by').val('created');
		});


	});
</script>